archivebox:
    # method :docker-compose, python.
    method: docker-compose
    # path containing archivebox data. When using docker-compose method, must be the path of the docker-compose file (the path will be the one in the .env file).
    path: ./
    # environment variables to be used when running archivebox (see archivebox docs).
    environment:
        - USE_COLOR=True
        - SHOW_PROGRESS=False
        - TIMEOUT=120
        - MEDIA_TIMEOUT=300
configuration:
    timezone: Europe/Paris
archives:
    # - name: name of the archive
    #   depth: depth of archive (0 or 1).
    #   sources: files containing urls.
    #       text_files: files containing one urls by line.
    #       shaarli: html files exported by shaarli.
    #       reddit_saved: files containing one urls by line (same as text_files).
    #       firefox_bookmarks: html files containing firefox bookmarks.
    #       firefox_history: json files exported with the export_browser_history.sh script in archivebox repository.
    #   schedule: optional. Possible values are daily, weekly, monthly or yearly. See README.md for more informations.
    - name: example
      depth: 0
      sources:
          text_files:
              - text1.txt
              - text2.txt
          shaarli:
              - shaarli.html
          reddit_saved:
              - reddit_saved.html
          firefox_bookmarks:
              - firefox_bookmarks.html
          firefox_history:
              - firefox_history.html
    - name: daily
      depth: 0
      sources:
          text_files:
              - URLs/daily.txt
      schedule: daily
    - name: weekly
      depth: 0
      sources:
          text_files:
              - URLs/weekly.txt
      schedule: weekly
    - name: monthly
      depth: 0
      sources:
          text_files:
              - URLs/monthly.txt
      schedule: monthly
    - name: yearly
      depth: 0
      sources:
          text_files:
              - URLs/yearly.txt
      schedule: yearly
    - name: shaarli
      depth: 0
      sources:
          shaarli_files:
              - bookmarks_shaarli.html
    - name: reddit-saved
      depth: 0
      sources:
          reddit_saved:
              - reddit_saved_user1.txt
              - reddit_saved_user2.txt
    - name: firefox
      depth: 0
      sources:
          firefox_bookmarks:
              - bookmarks_firefox.html
          firefox_history:
                - history_firefox.html
